OpenFLUID/openfluid

.travis.yml, CMake.in.cmake, CMakeLists.txt
* Updated travis-ci config file
* Switched to version 2.1.0~beta4
=> Update configuration for waresdev source code integration

resources/CMakeLists.txt, resources/tools/ofsrc-stylecheck.py
* Added Python script for checking style in source code
* Added checkstyle target in CMake configuration for easy run
of style checking
=> Introduction of automatic tool for coding style checking

src/openfluid/landr/LandRGraph.cpp, src/openfluid/landr/LandRGraph.hpp, src/openfluid/landr/LandRTools.cpp, src/openfluid/landr/LandRTools.hpp, src/openfluid/landr/LineStringGraph.cpp, src/openfluid/landr/LineStringGraph.hpp, src/openfluid/landr/PolygonEntity.hpp, src/openfluid/landr/PolygonGraph.cpp, src/openfluid/landr/PolygonGraph.hpp, src/openfluid/landr/RasterDataset.hpp, src/openfluid/landr/VectorDataset.cpp, src/openfluid/landr/VectorDataset.hpp, src/openfluid/landr/tests/LandRGraph_TEST.cpp, src/openfluid/landr/tests/LandRTools_TEST.cpp, src/openfluid/landr/tests/PolygonEntity_TEST.cpp, src/openfluid/landr/tests/RasterDataset_TEST.cpp, src/openfluid/landr/tests/VectorDataset_TEST.cpp
* Add method to create index field list for VectorDataset
* Modified code to avoid using float
* Modified code to follow coding style
=> Add udpate field method for VectorDataset

src/openfluid/landr/LandRGraph.cpp, src/openfluid/landr/LandRTools.cpp, src/openfluid/landr/LineStringEntity.cpp, src/openfluid/landr/LineStringGraph.cpp, src/openfluid/landr/PolygonEdge.cpp, src/openfluid/landr/PolygonEntity.cpp, src/openfluid/landr/PolygonGraph.cpp, src/openfluid/landr/PolygonGraph.hpp, src/openfluid/landr/RasterDataset.cpp, src/openfluid/landr/VectorDataset.cpp, src/openfluid/landr/tests/PolygonGraph_TEST.cpp
* Enhanced methods by adding neighbour option
* Added OPENFLUID_CODE_LOCATION definition
=> Enhance methods for identifying Polygon with form or area threshold

CHANGELOG, README.md, doc/contents/apdx_values.dox, doc/contents/dev_srccode.dox, doc/contents/mainpage.dox, doc/layout/main.tex.in
* Updated main documentation according to new string representations
for OpenFLUID values
* Updated CHANGELOG
* Updated dependencies list in README.md file
(closes OpenFLUID/openfluid#561)
=> Update of documentation

resources/tests/datasets/OPENFLUID.IN.Generators/checkgenerators.fluidx, src/openfluid/machine/InjectGenerator.cpp, src/tests/simulators/tests.generators/GeneratorsSim.cpp
* Fixed variable production for vector type
* Updated tests
=> Fix of inject generator

src/apps/openfluid-builder/common/WareWidget.cpp, src/apps/openfluid-builder/common/WareWidget.hpp, src/apps/openfluid-builder/common/WareWidget.ui, src/apps/openfluid-builder/model/GeneratorGraphics.cpp, src/apps/openfluid-builder/model/GeneratorGraphics.hpp, src/apps/openfluid-builder/model/ModelItemGraphics.cpp, src/apps/openfluid-builder/model/ModelItemGraphics.hpp, src/apps/openfluid-builder/model/ModelScene.cpp, src/apps/openfluid-builder/model/SimulatorGraphics.cpp, src/apps/openfluid-builder/model/SimulatorGraphics.hpp
* Added simulator and generator order in both management 
and graphical view of models
* Added observer order in management of monitoring
=> Add of ware order in OpenFLUID-Builder

src/openfluid/tools/Filesystem.cpp, src/openfluid/tools/MiscHelpers.cpp, src/openfluid/tools/MiscHelpers.hpp, src/openfluid/tools/tests/Filesystem_TEST.cpp, src/openfluid/tools/tests/MiscHelpers_TEST.cpp
* Added generator of pseudo-unique identifiers
* Updated method to create unique subdirectories 
with names based on PID and pseudo-unique identifier
* Cleaned code
(closes OpenFLUID/openfluid#676)
=> Improvements in creation of unique directories

src/openfluid/core/Matrix.hpp, src/openfluid/core/Vector.hpp, src/openfluid/core/VectorValue.hpp, src/tests/simulators/tests.fortran/FortranSim.cpp, src/tests/simulators/tests.fortran90/Fortran90Sim.cpp
* Updated Matrix destructor
* Updated Fortran tests
* Cleaned code
(closes OpenFLUID/openfluid#703)
(closes OpenFLUID/openfluid#704)
=> Fix of potential memory leaks

src/apps/openfluid-builder/spatial/SpatialDomainWidget.cpp, src/apps/openfluid-builder/spatial/SpatialDomainWidget.hpp
* Added attribute line/cell selection detection and sync by id table
* Added id table line selection detection and sync by map
(closes OpenFLUID/openfluid#350)
=> Sync map selection with attribute table line

src/apps/openfluid-builder/model/AddGeneratorDialog.cpp, src/apps/openfluid-builder/runconfig/RunConfigurationWidget.cpp, src/apps/openfluid-builder/spatial/AddUnitsClassDialog.cpp, src/apps/openfluid-builder/spatial/SpatialDomainWidget.cpp, src/openfluid/ui/waresdev/WareBuildOptionsWidget.cpp
* units process order (in Builder and dialog)
* thread number and memory steps (in Builder)
* vector dimensions (in generator dialog)
* jobs number for building (in waresdev)
(closes OpenFLUID/openfluid#819)
=> Adjust several spinbox ranges to c++ max int value

src/apps/openfluid-builder/spatial/MapScene.cpp, src/apps/openfluid-builder/spatial/MapScene.hpp, src/apps/openfluid-builder/spatial/SpatialDomainWidget.cpp
* Implemented shift selection via attribute selection
* Optimized map selection algorithm
(closes OpenFLUID/openfluid#822)
=> Shift selection on map in builder

examples/simulators/water.surf-uz.runoff-infiltration.mseytoux/MorelSeytouxSim.cpp, examples/simulators/water.surf.transfer-rs.hayami/HayamiRSSim.cpp, examples/simulators/water.surf.transfer-su.hayami/HayamiSUSim.cpp
* Deleted unused variables
* Corrected variable order in constructor
=> Correction of MHYDAS simulators warnings

src/observers/export.vars.files.csv-multicols/EditClassIDVarDialog.ui
* Added a container to set explicit unit class radiobuttons group
=> Radiobutton bug fix for multicolumn edit dialog in Builder

share/openfluid/waresdev/cpp.syntaxhl.ofdev.xml, src/apps/openfluid-devstudio/MainWindow.cpp, src/apps/openfluid-devstudio/MainWindow.hpp, src/openfluid/base/PreferencesManager.cpp, src/openfluid/base/PreferencesManager.hpp, src/openfluid/ui/common/PreferencesDialog.cpp, src/openfluid/ui/common/PreferencesDialog.hpp, src/openfluid/ui/common/PreferencesDialog.ui, src/openfluid/ui/waresdev/WareSrcFileEditor.cpp, src/openfluid/ui/waresdev/WareSrcWidget.cpp, src/openfluid/ui/waresdev/WareSrcWidget.hpp, src/openfluid/ui/waresdev/WareSrcWidgetCollection.cpp, src/openfluid/ui/waresdev/WareSrcWidgetCollection.hpp, src/tests/simulators/tests.generators.cycle.prod/GeneratorCycleProd.cpp, src/tests/simulators/tests.generators.cycle.use/GeneratorCycleUse.cpp, src/tests/simulators/tests.na.randomtime/RandomTimeSim.cpp
DevStudio adjustments:
- Invisible characters
- "Save as" behaviour
=> Devstudio save as 1009

src/apps/openfluid-devstudio/MainWindow.cpp, src/apps/openfluid-devstudio/MainWindow.hpp, src/apps/openfluid-devstudio/WareBuildStatusWidget.cpp, src/apps/openfluid-devstudio/WareBuildStatusWidget.hpp, src/openfluid/ui/waresdev/WareBuildOptionsWidget.cpp, src/openfluid/ui/waresdev/WareSrcWidget.cpp, src/openfluid/waresdev/WareBuildOptions.hpp
* Adjusted variable names
* Fixed interface between main window and build status widget
=> DevStudio build options implementation cleaning

src/apps/openfluid-builder/model/AddGeneratorDialog.cpp, src/observers/export.vars.files.csv-multicols/src/EditClassIDVarDialog.cpp, src/observers/export.vars.files.csv-multicols/src/MultiCSVFilesObs.cpp, src/observers/export.vars.files.csv/src/CSVFilesObs.cpp, src/observers/export.vars.files.csv/src/EditSetDialog.cpp, src/openfluid/config.hpp.in, src/openfluid/fluidx/FluidXIO.cpp, src/openfluid/machine/MultiInjectGenerator.cpp, src/openfluid/machine/tests/Generator_TEST.cpp, src/openfluid/tools/DistributionBindings.cpp, src/openfluid/tools/VarHelpers.cpp, src/openfluid/tools/VarHelpers.hpp
* fixed errors in multicolumn injection
(closes OpenFLUID/openfluid#1181)
skip-checks:true
=> Multicolumn generator edge cases handling

resources/translations/openfluid-fr_FR.ts, src/openfluid/ui/waresdev/WareSrcWidget.cpp, src/openfluid/ui/waresdev/WareSrcWidgetCollection.cpp
(co-authored by: Dorian Gerardin)
=> French translations for apps UI of version 2.2

doc/contents/apdx_generators.md, doc/contents/apdx_multicolumn-generators.md, doc/contents/apdx_tpl_signature.md, doc/contents/dev_signature.md, doc/layout/main.tex.in
* added doc for template signature
* added dpc for multi-type generator
* simplified signature doc
* fixed image display in generators doc
=> Doxygen documentation improvements

.githooks/pre-push, resources/tools/ofsrc-stylecheck.py
* added pre-push hook (for manual add in .git/hooks) about stylecheck and wip control
* dramatically improved stylecheck
=> Git pre-push hook

.githooks/pre-push
* fixed work in progress tag detection in commit text
=> More strict git hook

resources/tests/miscsrc/wares-dev-201xx/sim/tests.cmdline.sim-migration/REF/openfluid-ware.json, resources/tests/miscsrc/wares-dev-201xx/sim/tests.cmdline.sim-migration/wareshub.json, src/apps/openfluid/tests/CMakeLists.txt
* added control of issue conversion
=> Improvement of ware migration test

resources/translations/openfluid-fr_FR.ts
(co-authored-by: Armel THÖNI <armel.thoni@inrae.fr>)
=> Improved FR translation

src/openfluid/utils/Binding.hpp, src/openfluid/utils/tests/Binding_TEST.cpp
* Fixed re-opening of project via openProject
=> Fix of project opening bug in Bindings
